"""Deterministic domain model for the support-agent learning project."""

from .domain import (
    AddressMatchResult,
    AuditEvent,
    CarrierEvidenceSnapshot,
    CaseStatus,
    CustomerReference,
    CustomerReport,
    Disposition,
    ExecutionStatus,
    FollowUpStatus,
    MatchStatus,
    OperationalIntegrityAlert,
    OrderReference,
    RetrievalStatus,
    ShipmentReference,
    StateSnapshot,
    SupportCase,
    TransitionRejected,
)

__all__ = [
    "AddressMatchResult",
    "AuditEvent",
    "CarrierEvidenceSnapshot",
    "CaseStatus",
    "CustomerReference",
    "CustomerReport",
    "Disposition",
    "ExecutionStatus",
    "FollowUpStatus",
    "MatchStatus",
    "OperationalIntegrityAlert",
    "OrderReference",
    "RetrievalStatus",
    "ShipmentReference",
    "StateSnapshot",
    "SupportCase",
    "TransitionRejected",
]
