"""Deterministic domain model for the support-agent learning project."""

from .domain import (
    AddressMatchResult,
    AuditEvent,
    CarrierEvidenceSnapshot,
    CaseStatus,
    CustomerReference,
    CustomerReport,
    Disposition,
    ExecutionStatus,
    FollowUpStatus,
    HumanReviewDecision,
    HumanReviewRequest,
    MatchStatus,
    OperationalIntegrityAlert,
    OrderReference,
    PolicyEvaluationResult,
    PolicyPlaceholder,
    PolicyRoute,
    RetrievalStatus,
    ShipmentReference,
    StateSnapshot,
    SupportCase,
    TransitionRejected,
    evaluate_synthetic_structural_policy,
)

__all__ = [
    "AddressMatchResult",
    "AuditEvent",
    "CarrierEvidenceSnapshot",
    "CaseStatus",
    "CustomerReference",
    "CustomerReport",
    "Disposition",
    "ExecutionStatus",
    "FollowUpStatus",
    "HumanReviewDecision",
    "HumanReviewRequest",
    "MatchStatus",
    "OperationalIntegrityAlert",
    "OrderReference",
    "PolicyEvaluationResult",
    "PolicyPlaceholder",
    "PolicyRoute",
    "RetrievalStatus",
    "ShipmentReference",
    "StateSnapshot",
    "SupportCase",
    "TransitionRejected",
    "evaluate_synthetic_structural_policy",
]
